# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

csFs <- function(uIn, vIn, wIn, ZIn, ustarIn, LinvIn, ZoIn, bwIn, sUustarIn, sVustarIn, kvIn, C0In, alphaIn, MaxFetchIn, outSteps) {
    .Call(`_traxr_csFs`, uIn, vIn, wIn, ZIn, ustarIn, LinvIn, ZoIn, bwIn, sUustarIn, sVustarIn, kvIn, C0In, alphaIn, MaxFetchIn, outSteps)
}

csFi <- function(uIn, vIn, wIn, ZIn, ustarIn, LinvIn, ZoIn, bwIn, sUustarIn, sVustarIn, kvIn, C0In, alphaIn, MaxFetchIn, outSteps) {
    .Call(`_traxr_csFi`, uIn, vIn, wIn, ZIn, ustarIn, LinvIn, ZoIn, bwIn, sUustarIn, sVustarIn, kvIn, C0In, alphaIn, MaxFetchIn, outSteps)
}

